class CreateAcMotors < ActiveRecord::Migration
  def self.up
    create_table :ac_motors do |t|
    	t.string :motor_size
    	t.string :arm_part_no
		t.string :armature_drw
		t.string :field_part_no
		t.string :field_drw
		t.string :voltage
		t.string :power
		t.string :amps_rating
		t.string :output_rpm
		t.string :rotation
		t.string :no_load_rpm_motor
		t.string :gear_ratio
		t.string :arm_wire_dia
		t.string :field_wire_dia
		t.string :winding_type
		t.string :arm_resistance
		t.string :displace_angle
		t.string :arm_no_of_turns
		t.string :field_no_of_turns
		t.string :field_resistance
		t.string :field_wind_drw
		t.string :arm_package
		t.string :shaft_part_no
		t.string :shaft_drw
		t.string :arm_stack
		t.string :arm_laminate
		t.string :field_stack
		t.string :field_stack_opt
		t.string :arm_end_lami
		t.string :molding_comp
		t.string :commutator
		t.string :arm_copper_wire
		t.string :arm_wire_drw
		t.string :field_copper_wire
		t.string :arm_fan
		t.string :insulating_tube
		t.string :insulator
		t.string :hard_paper_tube
		t.string :slot_insulation
		t.string :slot_wedge
		t.string :pressboard
		t.string :field_insulation_paper
		t.string :connection_plate
		t.string :conn_plate_opt
		t.string :end_plate
		t.string :end_plate_opt
		t.string :polyester_resin
		t.string :resin_hardener
		t.string :hardener_adhesive
		t.string :impregnating_resin
		t.string :impreg_hardener
		t.string :receptacle_01
		t.string :receptacle_02
		t.string :field_impregn_resin
		t.string :field_resin_hard
		t.string :filed_coating
		t.string :field_heat_sink
		t.string :field_pressboard
		t.string :where_used_product
		t.string :where_used_plant
		t.string :remark
		t.string :release_status
		t.string :uploaded_by_section
		t.string :uploader_role
		t.string :uploader_name
		t.boolean :need_to_edit_arm_part_no
		t.boolean :need_to_edit_motor_size
		t.boolean :need_to_edit_armature_drw
		t.boolean :need_to_edit_field_part_no
		t.boolean :need_to_edit_field_drw
		t.boolean :need_to_edit_voltage
		t.boolean :need_to_edit_power
		t.boolean :need_to_edit_amps_rating
		t.boolean :need_to_edit_output_rpm
		t.boolean :need_to_edit_rotation
		t.boolean :need_to_edit_no_load_rpm_motor
		t.boolean :need_to_edit_gear_ratio
		t.boolean :need_to_edit_arm_wire_dia
		t.boolean :need_to_edit_field_wire_dia
		t.boolean :need_to_edit_winding_type
		t.boolean :need_to_edit_arm_resistance
		t.boolean :need_to_edit_displace_angle
		t.boolean :need_to_edit_arm_no_of_turns
		t.boolean :need_to_edit_field_no_of_turns
		t.boolean :need_to_edit_field_resistance
		t.boolean :need_to_edit_field_wind_drw
		t.boolean :need_to_edit_arm_package
		t.boolean :need_to_edit_shaft_part_no
		t.boolean :need_to_edit_shaft_drw
		t.boolean :need_to_edit_arm_stack
		t.boolean :need_to_edit_arm_laminate
		t.boolean :need_to_edit_field_stack
		t.boolean :need_to_edit_field_stack_opt
		t.boolean :need_to_edit_arm_end_lami
		t.boolean :need_to_edit_molding_comp
		t.boolean :need_to_edit_commutator
		t.boolean :need_to_edit_arm_copper_wire
		t.boolean :need_to_edit_arm_wire_drw
		t.boolean :need_to_edit_field_copper_wire
		t.boolean :need_to_edit_arm_fan
		t.boolean :need_to_edit_insulating_tube
		t.boolean :need_to_edit_insulator
		t.boolean :need_to_edit_hard_paper_tube
		t.boolean :need_to_edit_slot_insulation
		t.boolean :need_to_edit_slot_wedge
		t.boolean :need_to_edit_pressboard
		t.boolean :need_to_edit_field_insulation_paper
		t.boolean :need_to_edit_connection_plate
		t.boolean :need_to_edit_conn_plate_opt
		t.boolean :need_to_edit_end_plate
		t.boolean :need_to_edit_end_plate_opt
		t.boolean :need_to_edit_polyester_resin
		t.boolean :need_to_edit_resin_hardener
		t.boolean :need_to_edit_hardener_adhesive
		t.boolean :need_to_edit_impregnating_resin
		t.boolean :need_to_edit_impreg_hardener
		t.boolean :need_to_edit_receptacle_01
		t.boolean :need_to_edit_receptacle_02
		t.boolean :need_to_edit_field_impregn_resin
		t.boolean :need_to_edit_field_resin_hard
		t.boolean :need_to_edit_filed_coating
		t.boolean :need_to_edit_field_heat_sink
		t.boolean :need_to_edit_field_pressboard
		t.boolean :need_to_edit_where_used_product
		t.boolean :need_to_edit_where_used_plant
		t.boolean :need_to_edit_remark
		t.timestamps
    end
  end

  def self.down
  	drop_table :ac_motors
  end
end
